version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/openjdk:17
    steps:
      - checkout
      - run:
          name: Install Maven
          command: sudo apt-get install -y maven
      - run:
          name: Install kt lint
          command: |
            curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.49.1/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/
      - run:
          name: Install dependencies
          command: mvn clean install
      - run:
          name: Test
          command: mvn test
      - run:
          name: Check Code Formatting with ktlint
          command: ktlint

workflows:
  sample:
    jobs:
      - build-and-test

triggers:
  - push:
      branches:
        - 'feature/kotlin'